DEFAULT_SITE_CONTENT: dict[str, str] = {
    "page_badge": "بوابة خدمات أبسط",
    "hero_title": "طلبك يبدأ هنا،",
    "hero_highlight": "ومتابعته أسهل.",
    "hero_description": "أرسل بيانات الخدمة مرة واحدة، وتابع حالتها واستقبل كل التحديثات المهمة من حسابك.",
    "point_1_title": "حالة واضحة",
    "point_1_text": "تعرف أين وصل طلبك بدون رسائل متفرقة.",
    "point_2_title": "بيانات محمية",
    "point_2_text": "نستخدم ضوابط أمنية مخصصة لحماية بيانات الدخول.",
    "story_footer": "Talab · بوابة العملاء والخدمات",
    "form_kicker": "الخطوة 1 من 1",
    "form_title": "إنشاء طلب جديد",
    "form_description": "أدخل بياناتك كما تريد استخدامها في الخدمة، ثم اختر نوع الطلب.",
    "full_name_label": "الاسم الكامل",
    "phone_label": "رقم الجوال",
    "username_label": "اسم المستخدم",
    "username_hint": "سيُستخدم أيضًا لمتابعة حسابك",
    "password_label": "كلمة المرور",
    "password_hint": "6 أحرف على الأقل",
    "service_type_label": "نوع الخدمة",
    "service_type_placeholder": "اختر نوع الخدمة",
    "service_label": "الخدمة المطلوبة",
    "service_placeholder": "اختر الخدمة المطلوبة",
    "other_option": "أخرى — اكتب طلبك",
    "other_service_label": "صف الخدمة المطلوبة",
    "other_service_placeholder": "اكتب وصفًا مختصرًا يساعدنا على فهم المطلوب...",
    "submit_button": "إرسال الطلب",
    "login_prompt": "لديك حساب بالفعل؟",
    "login_link": "تسجيل الدخول",
    "success_kicker": "تم بنجاح",
    "success_title": "وصلنا طلبك",
    "success_body": "تم إنشاء حسابك وحفظ طلبك بحالة قيد المراجعة. سجل دخولك في أي وقت لمتابعة الحالة والإشعارات.",
    "success_button": "الانتقال لتسجيل الدخول",
    "success_note": "لن تحتاج لإرسال بيانات طلبك مرة أخرى عبر المحادثات.",
    "terms_prefix": "قرأت وأوافق على",
    "terms_link": "شروط الخدمة وسياسة الاستخدام",
}

EDITABLE_SITE_CONTENT_KEYS = frozenset(DEFAULT_SITE_CONTENT)
MAX_SITE_CONTENT_VALUE_LENGTH = 2500
